config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  post '/resultado', to: 'home#resultado'

  get '/sobre', to: 'home#sobre'
  get 'home/index', to: 'home#index'
  post '/index', to: 'home#index'

  post '/palavras', to: 'home#palavras'
  get '/palavras', to: 'home#palavras'

  post '/check_answer', to: 'home#check_answer'

  post '/work_random', to: 'home#work_random'

  get '/gerar_qr_code', to: 'home#gerar_qr_code'
  post '/gerar_qr_code', to: 'home#gerar_qr_code'

  get 'download_qr_code', to: 'home#download_qr_code', as: 'download_qr_code'


  get '/edit_word', to: 'home#edit_word'
  post '/edit_word', to: 'home#edit_word'

  get '/index2', to: 'home#index2'
  post '/index2', to: 'home#index2'

  get '/calculate_index2', to: 'home#calculate_index2'
  post '/calculate_index2', to: 'home#calculate_index2'

  get '/love_porce', to: 'home#love_porce'
  post '/love_porce', to: 'home#love_porce'

  get '/imc', to: 'home#imc'
  post '/imc', to: 'home#imc'

  get '/termo2', to: 'home#termo2'
  post '/termo2', to: 'home#termo2'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @numero_whatsapp = "+554999482859"
    @meu_nome = params[:nome]

    $num1 = rand(0..10)
    $num2 = rand(0..10)

    @palavra = params[:palavra]

    if @palavra.present?
      @reverse = @palavra.reverse
      flash[:notice] = "Palavra Invertida: #{@reverse}"
    else
      flash.delete(:notice)  # Certificando-se de limpar a flash se não houver palavra presente
    end

    @x = Time.new
    if @x.present?
      flash[:notice_2] = "Data Atual: #{@x}"
    end

    @original_word = params[:original_word]
    if @original_word.present?

      @word = @original_word.chars.shuffle.join
      flash[:notice_word_2] = "Palavra Embaralhada: #{@word}"

    end
  end

  def resultado
    @numero1 = params[:nm1].to_f
    @numero2 = params[:nm2].to_f
    @operador = params[:operacao]

    @resultado =
    case @operador
    when "+"
      @numero1 + @numero2

    when "-"
      @numero1 - @numero2

    when "x"
      @numero1 * @numero2

    when "÷"
      @numero1 / @numero2

    end
  end

  def palavras
    @palavra = params[:work]
    @quantidade = params[:qnt].to_i

    @resultado = ''

    @quantidade.times do |i|
    @resultado += @palavra

    @resultado += ', ' unless i == @quantidade - 1

    end
  end

  def check_answer
    @minha_resposta = params[:tentativa].to_i

    @resposta_correta = $num1 + $num2

  end

  def work_random
    @quantia_letras = params[:letras].to_i

    @word = Cicero.words(@quantia_letras)

  end

  def gerar_qr_code
    @url = params[:url]
    #@size = params[:size].to_i
  
    qr = RQRCode::QRCode.new(@url)
    @png = qr.as_png(
      bit_depth: 1,
      border_modules: 4,
      color_mode: ChunkyPNG::COLOR_GRAYSCALE,
      color: "black",
      file: nil,
      fill: "white",
      module_px_size: 6,
      resize_exactly_to: false,
      resize_gte_to: false,
      size: 500
    )
  
    flash[:notice_qr_code] = "Link: #{@url}"
  end

  def download_qr_code
    url = params[:url]
    module_size = 10  
    
    qr = RQRCode::QRCode.new(url, size: module_size, level: :h)
    png = qr.as_png(size: 500)
    
    send_data png.to_s, type: 'image/png', disposition: 'attachment', filename: 'qr_code.png'
  end

  def edit_word
    @word = params[:word]
  end

  def sobre
    render layout: 'no-back'

  end

  def palavra_2
    texto.split('').shuffle.join('')

  end

  # def index2
  #   render layout: 'back_index'

  #   @lista = params[:lista]
  #   if @lista.present?
  #     flash[:notice] = "Sua lista: #{@lista}"

  #   else
  #     flash.delete(:notice)

  #   end

  # end

  def index2
    @lista = params[:lista].to_i
    f = @lista.to_s.split('').map(&:to_i) # dividir a string em caracteres individuais e convertê-los para inteiros

    def insertionsort(f)
      for i in (1...f.length)
        key = f[i]
        j = i - 1

        while j >= 0 and key < f[j]
          f[j + 1] = f[j]
          j -= 1
        end

        f[j + 1] = key
      end
      return f
    end

    if @lista.present?
      flash[:notice] = "Sua lista ordenada: #{insertionsort(f)}"
    else
      flash.delete(:notice)
    end

    render :index2
  end

  def calculate_index2
    @nm = params[:numero].to_s.split('').map(&:to_i)
    sum = @nm.sum

    if @nm.present?
      flash[:notice2] = "A soma de todos os números é: #{sum}"
    else
      flash.delete(:notice2)
    end

    render :index2
  end

  def love_porce
    @nome1 = params[:nome1].to_s
    @nome2 = params[:nome2].to_s
    k = rand(0..101)

    if k >= 0 && k < 10
      flash[:notice3] = "esquece abafa nem tenta"
    elsif k >= 11 && k < 20
      flash[:notice3] = "quer se incomodar compra um fusca"
    elsif k >= 21 && k < 30
      flash[:notice3] = "ta bom mas ta ruim"
    elsif k >= 31 && k < 40
      flash[:notice3] = "com jeitinho até dá"
    elsif k >= 41 && k < 50
      flash[:notice3] = "sepá que sim sepá que não"
    elsif k >= 51 && k < 60
      flash[:notice3] = "opa tem chance"
    elsif k >= 61 && k < 70
      flash[:notice3] = "Ta legal já dá pra beja"
    elsif k >= 71 && k < 80
      flash[:notice3] = "É VAPO É DENTRO"
    elsif k >= 81 && k < 90
      flash[:notice3] = "TALOCO QUE ROMÂNTICO"
    elsif k >= 91 && k < 100
      flash[:notice3] = "VAMOOOO CARALHO SE AMAM PRA PORRA"

    elsif @nome1 == "Gabriel" && @nome2 == "Laura"
      flash[:notice3] = "MEU CASAL LINDOS SE AMAM MUITO"

    else
      flash[:notice3] = "Algo deu errado. Tente novamente."
    end

    render :index2
  end

  def imc
    @p = params[:p].to_f
    @a = params[:a].to_f

    imc = @p / (@a ** 2)

    if @p > 0 && @a > 0
      if imc < 18.5
        flash[:imc] = "Magreza.<br>Seu IMC é de: #{imc.ceil(2)}".html_safe

      elsif imc >= 18.5 && imc < 24.9
        flash[:imc] = "Peso normal.<br> Seu IMC é de: #{imc.ceil(2)}.".html_safe

      elsif imc >= 25 && imc < 29.9
        flash[:imc] = "Sobrepeso - I.<br> Seu IMC é de: #{imc.ceil(2)}".html_safe

      elsif imc >= 30 && imc < 39.9
        flash[:imc] = "Obesidade - II.<br> Seu IMC é de: #{imc.ceil(2)}".html_safe

      elsif imc > 40
        flash[:imc] = "Obesidade Grav - III.<br> Seu IMC é de: #{imc.ceil(2)}".html_safe

      end
    end

    render :index2
  end

  def termo2
    @qnt_letras = params[:qnt].to_i

    letras = ('a'..'z').to_a  # Array contendo todas as letras do alfabeto
    aleatorias = Array.new(@qnt_letras) { letras.sample }  # Seleciona aleatoriamente n letras do array
    x = aleatorias.join("")
    flash[:woks] = x
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_calculate_index2.html.erb
<div class='Form-2-index2'>
    <%= form_tag( '/calculate_index2', remote: true) do |f| %>
        <%= label_tag :numero, "Digite alguns números" %>
        <%= text_field_tag :numero %>
        <%= submit_tag 'Mostrar soma de todos os númros' %>

        <% if flash[:notice2].present? %>
            <%= flash[:notice2] %>
            
        <% end %>
    <% end %>               
</div>

app/views/home/_imc.html.erb
<div class='Form-4-index2'>
  <%= form_tag('/imc', remote: true) do |f| %>
    <%= label_tag :p, "Digite seu peso" %>
    <%= text_field_tag :p %>
    
    <%= label_tag :a, "Digite a sua altura (Ex: 1.75)" %>
    <%= text_field_tag :a %>
    
    <%= submit_tag 'Calcular IMC' %>

    <% if flash[:imc].present? %>
      <%= flash[:imc] %>
    <% end %>
  <% end %>               
</div>

app/views/home/_love_porce.html.erb
<div class='Form-3-index2'>
  <%= form_tag('/love_porce', remote: true) do |f| %>
    <%= label_tag :nome1, "Digite o primeiro nome" %>
    <%= text_field_tag :nome1 %>
    
    <%= label_tag :nome2, "Digite o segundo nome" %>
    <%= text_field_tag :nome2 %>
    
    <%= submit_tag 'Calcular porcentagem de amor' %>

    <% if flash[:notice3].present? %>
      <%= flash[:notice3] %>
    <% end %>
  <% end %>               
</div>

app/views/home/check_answer.erb
<div class="content">

  <% if @minha_resposta == @resposta_correta %>
    <p>Resposta correta!</p>
    
  <% else  %>
    <p>Resposta incorreta!, resultado correto: de <%= $num1 %> + <%= $num2%>: <%= @resposta_correta %></p>

  <% end %>

  <%= link_to "Voltar", './', class: 'link-voltar' %>

</div>

app/views/home/check_answer.html.erb
<div class="content">

  <% if @minha_resposta == @resposta_correta %>
    <p>Resposta correta!</p>
    
  <% else  %>
    <p>Resposta incorreta!, resultado correto: de <%= $num1 %> + <%= $num2%>: <%= @resposta_correta %></p>

  <% end %>

  <%= link_to "Voltar", './', class: 'link-voltar' %>

</div>

app/views/home/edit_word.html.erb
<div class="edit_word">
  <div class="Form-10">
    <%= form_tag('/edit_word', remote: true) do |f| %>
      <%= label_tag :word, "Informe a palavra a ser modificada: " %>
      <%= text_field_tag :word %><br>

      <%= label_tag "A Fonte" %>

      <%= label_tag 'font', 'Kode Mono' %>
      <%= check_box_tag 'font', 'Kode Mono', false %><br>
      
      <%= label_tag 'font', 'Jacquarda Bastarda 9' %>
      <%= check_box_tag 'font', 'Jacquarda Bastarda 9', false  %><br>
      
      <%= label_tag 'font', 'Padrão' %>
      <%= check_box_tag 'font', 'Padrao', false %><br>
      
      <%= label_tag 'font', 'Macodo(static)'%>
      <%= check_box_tag 'font', 'Macodo', false%><br>

      <%= label_tag 'font', 'Ubuntu Condensed (static)'%>
      <%= check_box_tag 'font', 'Ubuntu Condensed' %><br>

      <%= submit_tag 'Modificar' %>
      <%= link_to "Voltar", './', class:'link-voltar-2' %>

    <% end %>
  </div>

  <div class='Form-10'>
    <div class="mural">
      <h1>Exemplo Fontes: </h1>
      <span>Fonte-Kode Mono: <p style='font-family: "Kode Mono", monospace;"'>Sua String aqui</p></span>
      <span>Fonte-Madimi One (Padrão): <p style='font-family: "Madimi One", sans-serif;"'>Sua String aqui</p></span>
      <span>Fonte-Jacquarda Bastarda 9: <p style='font-family: "Jacquarda Bastarda 9", serif;"'>Sua String aqui</p></span>
      <span>Fonte-Macondo (static): <p style='font-family: "Macondo", cursive;'>Sua String aqui</p></span>
      <span>Font-Ubuntu Condensed (static): <p style='font-family: "Ubuntu Condensed", sans-serif;'>Sua String aqui</p></span>
      <span></span>
    </div>
  </div>

  <div class='Form-10'>
    <div class='strings'>
      <h1>Texto modificado: </h1>
      <% if @word.present? %>
          <% if params[:font] == 'Kode Mono' %>
            <h2 style='font-family: "Kode Mono", monospace; text-decoration: underline;'> <%= @word %> </h2>

          <% elsif params[:font] == 'Padrao'%>
            <h2 style='font-family: "Madimi One", sans-serif; text-decoration: underline;'> <%= @word %> </h2>

          <% elsif params[:font] == 'Macodo' %>
            <h2 style='font-family: "Macondo", cursive;'> <%= @word %> </h2>

          <% elsif params[:font] == 'Ubuntu Condensed' %>
            <h2 style='font-family: "Ubuntu Condensed", sans-serif;'> <%= @word %></h2>

          <% elsif params[:font] == 'Jacquarda Bastarda 9' %>
            <h2 style='font-family: "Jacquarda Bastarda 9", serif; text-decoration: underline;'> <%= @word %> </h2>
          <% else %>
            <strong> Você esqueceu de escolher sua fonte!!! </strong>
            <h3>Seu Texto: <%= @word%></h3>
          <% end %>
      <% else %>
          <strong> Insira um texto! </strong>    
        <% end %>
    </div>
  </div>
</div>

app/views/home/gerar_qr_code.html.erb
<div class="content">
  <h2>QR Code Gerado:</h2>
  <% if flash[:notice_qr_code].present? %>
    <%= flash[:notice_qr_code] %>
  <% end %>
  <% if @png.present? %>
    <%= image_tag 'data:image/png;base64,' + Base64.encode64(@png.to_blob) %>
    <%= link_to 'Download QR Code (PNG)', download_qr_code_path(format: :png, size: params[:size], url: params[:url]), id: 'download_qr_code' %>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="Container">
  <div class='Form'>
    <%= form_tag( '/resultado' , remote: true) do |f| %>
      
      <label for="operacao">Selecione a operação:</label>
      <%= select_tag 'operacao', options_for_select([['Soma', '+'], ['Subtração', '-'], ['Multiplicação', 'x'], ['Divisão', '÷']]), class: 'operador' %><br>
      
      <%= label_tag :nm1, "Número 1:", class: 'nm1' %>
      <%= text_field_tag :nm1 %><br>

      <%= label_tag :nm2, "Número 2:", class: 'nm2' %>
      <%= text_field_tag :nm2%><br>
      <%= submit_tag 'Calcular', class: 'calcular' %>

    <% end %>
    
  </div>

  <div class="Form-2">
    <%= form_tag( '/palavras', remote: true) do  %>
        
        <%= label_tag :work, "Digite a palavra: "%>
        <%= text_field_tag :work %>

        <%= label_tag :qnt, "Quantidade: "%>
        <%= text_field_tag :qnt %>

        <%= submit_tag "Enviar" %>
    <% end %>
  </div>

  <div class="Form-3">
  <%= form_tag('/check_answer', method: 'post') do %>
    <p>
      <%= $num1 %> + <%= $num2  %> = <br>
      Resposta: <%= text_field_tag :tentativa %>

    </p>

    <%= submit_tag 'Verificar' %>

  <% end %>
  </div>

  <div class="Form-4">
    <%= form_tag('/work_random', remote: true) do %> 
      <%= label_tag :letras, "Quantidade de Caracter: "%>
      <%= text_field_tag :letras %>
      <%= submit_tag 'Gerar' %>
      
    <% end%>

  </div>

  <div class="Form-5">
    <%= form_tag('/index', method: :post, remote: true) do %>
    <%= label_tag :palavra, "Palavra: "%>
    <%= text_field_tag :palavra %>

    <%= submit_tag "Inverter" %>

    <% if flash[:notice].present? %>
      <%= flash[:notice] %>
    <% end %>
    
  <% end %>

  </div>

  <div class="Form-6">

  <%= form_tag('/gerar_qr_code', method: :post) do %>
    <%= label_tag :url, 'Insira uma URL:' %><br>
    <%= text_field_tag :url %><br>
  
    <%= submit_tag 'Gerar QR Code' %>
  <% end %>

  </div>

  <div class="Form-7">
    <%= form_tag( '/index' , remote: true) do |f| %>
      <%= submit_tag 'Exibir a hora' %>

      <% if flash[:notice_2].present? %>
        <%= flash[:notice_2] %>

      <% end %>
    <% end %>

  </div>

  <div class="Form-8">
  <%= form_tag('/index') do %>
    <%= label_tag 'color', 'Selecione uma cor:' %>
    <%= color_field_tag 'color', class: 'color-selector' %>
    <%= submit_tag 'Resetar' %>
  <% end %>

  </div>

    <div class='Form-9'>
      <%= link_to "Editar Palavra", edit_word_path, class:'Edit_word_a'%>
    </div>
</div>

app/views/home/index2.html.erb
<div class="Container-2">
    <div class='Form-1-index2'>
        <%= form_tag( '/index2', remote: true) do |f| %>
            <%= label_tag :lista, "Ordenar lista" %>
            <%= text_field_tag :lista %>
            <%= submit_tag 'Ordenar' %><br>

            <% if flash[:notice].present? %>
                <%= flash[:notice] %>
            
            <% end %>
        <% end %>               
    </div>

    <%= render "calculate_index2" %>
    <%= render "love_porce" %>
    <%= render "imc" %>
    <div class='Form-3-index2'>
        <%= form_tag('/termo2', remote: true) do |f| %>
            <%= label_tag :qnt, "Digite a quantidade de letras" %>
            <%= text_field_tag :qnt%>

            <%= submit_tag 'Gerar' %>

        <% end %>               
    </div>
</div>


<%= link_to "Voltar", './', class: 'link-voltar' %>

app/views/home/palavras.html.erb
<div class="content-2">
  <%= link_to "Voltar", './', class: 'link-voltar' %>
  <strong>Resultado: </strong> <%= @resultado %>
</div>

app/views/home/resultado.html.erb
<div class="content">
    <h2 class="resultado">O Resultado de <%= @numero1 %> <%= @operador %> <%= @numero2 %>: <%= @resultado %></h2>
    <%= link_to "Voltar", './', class: 'link-voltar' %>
    
</div>

app/views/home/sobre.html.erb
<%= stylesheet_link_tag "about-me" %>

<div class="about">
<div class="about-me">
    <section>
        <span class="text-1">Me chamo Gabriel Kochem Ichazo, tenho 17 de anos, atualmente estou 'cursando' informática na escola , em , Local onde nasci e moro atualmente.</span>
    </section>
</div>

    <div class="about-curri">
        <section>
            <span class="tecs">Tecnologias: <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/ruby/ruby-original.svg" alt="ruby" width="40" height="40"/> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/rails/rails-original-wordmark.svg" alt="rails" width="40" height="40"/> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40" height="40"/>  <%= image_tag "css-3-logo-svgrepo-com.png", class: 'css' %> <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Kotlin_Icon.svg/1024px-Kotlin_Icon.svg.png" %></span>
        </section>
    </div>
    <span class="tecs-2">Tecnologias do site: <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/ruby/ruby-original.svg" alt="ruby" width="40" height="40"/> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/rails/rails-original-wordmark.svg" alt="rails" width="40" height="40"/> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40" height="40"/> <%= image_tag "css-3-logo-svgrepo-com.png", class: 'css' %> </span>
</div>

app/views/home/termo2.html.erb
<h1> quantidade de letras: <%= flash[:woks] %>

<%= link_to "Voltar", 'http://[::1]:3000/index2', class: 'link-voltar' %>

app/views/home/work_random.html.erb
<div class="content-work">
    <%= link_to "Voltar", './', class: 'link-voltar' %>
    <p> Palavra Gerada: <%= @word %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "edit_word" %>
    <%= javascript_include_tag "color" %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Jacquarda+Bastarda+9&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Jacquarda+Bastarda+9&family=Kode+Mono:wght@400..700&family=Madimi+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Macondo&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Condensed&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Jacquarda+Bastarda+9&family=Kode+Mono:wght@400..700&display=swap" rel="stylesheet">  

    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.0/FileSaver.min.js"></script>

  </head>
  <body id="meu-body">
    <header class="Index-Header" id="meu-header"> <h1>Funcionalidades Legais </header>

    <nav>
      <%= link_to "Instagram", "https://www.instagram.com/o_tal_do_tsuki/", class: 'social-media_1', target: '_blank'  %>
      <%= link_to "GitHub", "https://github.com/TsukiKtk?tab=repositories", class: 'social-media_2', target: '_blank'  %>
      <%= link_to "Twitch", "https://www.twitch.tv/otaldotsuki", class: 'social-media_3', target: '_blank'  %>
      <%= link_to "WhatsApp", "https://wa.me/#{@numero_whatsapp}", class: 'social-meida_4', target: '_blank'  %>
      <%= link_to "E-mail", "mailto:gabikochem55@gmail.com", class: 'social-meida_5', target: '_blank' %>
      <%= link_to "Sobre", 'sobre', class: 'about' %> 
      <%= link_to "Index 2",  index2_path %>
      

    </nav>
      <%= yield %>

    <footer id="meu-footer">
      <p>&copy; 2024 Página Pessoal de: </p>
    </footer>


  </body>
  
</html>

app/views/layouts/no-back.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
  </head>

  <body>
  <header class="Index-Header"> <h1>Calculadora Topzera d+ </header>

  <nav>
    <%= link_to "Instagram", "https://www.instagram.com/o_tal_do_tsuki/", class: 'social-media_1', target: '_blank'  %>
    <%= link_to "GitHub", "https://github.com/TsukiKtk?tab=repositories", class: 'social-media_2', target: '_blank'  %>
    <%= link_to "Twitch", "https://www.twitch.tv/otaldotsuki", class: 'social-media_3', target: '_blank'  %>
    <%= link_to "WhatsApp", "https://wa.me/#{@numero_whatsapp}", class: 'social-meida_4', target: '_blank'  %>
    <%= link_to "E-mail", "mailto:gabikochem55@gmail.com", class: 'social-meida_5', target: '_blank' %>
    <%= link_to "Voltar", './', class: 'back' %>

  </nav>
    <%= yield %>

  <footer>
    <p>&copy; 2024 Página Pessoal de: <%= @meu_nome %></p>
  </footer>

  </body>
</html>